{% set name = "xcanvas" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xcanvas/archive/{{ version }}.tar.gz
  sha256: 6154f72dca8542ca738ad71e57ffe441f49cdd7f157dcb0a877170971a0fbd43

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - xtl >=0.7.0,<0.8
    - xproperty >=0.11.0,<0.12
    # TODO remove this when xwidgets run constraints is fixed
    - nlohmann_json =3.11.2
    - xwidgets >=0.28.1,<0.29
  run:
    - ipycanvas >=0.11.0,<0.12

test:
  commands:
    - test -d ${PREFIX}/include/xcanvas  # [unix]
    - test -f ${PREFIX}/include/xcanvas/xcanvas.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xcanvas/xcanvasConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xcanvas/xcanvasConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xcanvas\xcanvas.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xcanvasConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xcanvasConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/martinRenou/xcanvas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ back-end for ipycanvas
  dev_url: https://github.com/martinRenou/xcanvas

extra:
  recipe-maintainers:
    - JohanMabille
    - martinRenou
