context:
  version: "0.7.0"
  build_number: 0

package:
  name: xcanvas
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xcanvas/archive/${{ version }}.tar.gz
  sha256: 586de0aa53369e8e0804242186f85081bda674314d861fca7f7320815c09a4c9

build:
  number: ${{ build_number }}

requirements:
  run_exports:
    - ${{ pin_subpackage('xcanvas', upper_bound='x.x') }}
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then:
        - make
  host:
    - xproperty >=0.12.0,<0.13
    - xwidgets >=0.30,<0.31
    - nlohmann_json
    - nlohmann_json-abi
  run:
    - ipycanvas >=0.11.0,<0.12

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}include/xcanvas/xcanvas.hpp
          - ${{ "Library/" if win }}lib/cmake/xcanvas/xcanvasConfig.cmake
          - ${{ "Library/" if win }}lib/cmake/xcanvas/xcanvasConfigVersion.cmake

about:
  homepage: https://github.com/martinRenou/xcanvas
  repository: https://github.com/martinRenou/xcanvas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ back-end for ipycanvas

extra:
  recipe-maintainers:
    - JohanMabille
    - martinRenou
